name: 'Create/Update Azure policies'
description: 'An action to create/update Azure policies'
inputs: 
  paths:
    description: 'Path to current repository folder(s) which contains the policies to create/update'
    required: true
  ignore-paths:
    description: 'Folder(s) to ignore'
    required: false
  assignments:
    description: 'Only the assignments that match the expression(s) will be applied.'
    required: false
  enforcement-mode:
    description: '<TBD>'
    required: false
runs:
  using: 'node12'
  main: 'lib/run.js'