name: "Trigger Integration tests"
on:
  push:
    branches:
      - jysin/*
  pull_request:
    branches:
      - main
      - 'releases/*'
jobs: 
    trigger-integration-tests:
      name: Trigger Integration tests
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
          with:
              path: IntegrationTests

        - name: Extract branch name
          id: extract_branch
          run: |
            echo "##[set-output name=branchname;]$(echo ${GITHUB_REF##*/})"

        - name: Trigger Test run
          if: |
           github.event.pull_request.base.ref == 'releases/v0' || steps.extract_branch.outputs.branchname == 'releases/v0' || 
           github.event.pull_request.base.ref == 'main' || steps.extract_branch.outputs.branchname == 'main'
          run: |
              bash ./IntegrationTests/.github/workflows/InvokeL2RepoDispatchEvent.sh ${{ secrets.L2_REPO_TOKEN }} ${{ github.event.pull_request.head.sha }} ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }} 
           
